import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = (process.argv[2] === "production");

const obsidianContext = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

const webContext = await esbuild.context({
  entryPoints: ["index.tsx"],
  bundle: true,
  outfile: "dist/bundle.js",
  sourcemap: true,
  loader: { '.tsx': 'tsx', '.ts': 'ts' },
  logLevel: "info",
});

if (prod) {
  await obsidianContext.rebuild();
  await webContext.rebuild();
  await obsidianContext.dispose();
  await webContext.dispose();
  process.exit(0);
} else {
  await obsidianContext.watch();
  await webContext.watch();
  
  // Create .hotreload file for obsidian-hot-reload compatibility
  fs.writeFileSync(".hotreload", "");
  console.log("[Watch] Build started in watch mode.");
  console.log("[Watch] .hotreload file created.");
}